/*
 * Copyright 2013 Basho Technologies Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.basho.riak.client.core.operations;

import com.basho.riak.client.core.FutureOperation;
import com.basho.riak.client.core.RiakMessage;
import com.basho.riak.client.core.converters.CrdtResponseConverter;
import com.basho.riak.client.query.CrdtResponse;
import com.basho.riak.client.query.crdt.ops.*;
import com.basho.riak.client.query.crdt.types.CrdtElement;
import com.basho.riak.client.util.ByteArrayWrapper;
import com.basho.riak.client.util.RiakMessageCodes;
import com.basho.riak.protobuf.RiakDtPB;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.util.List;
import java.util.concurrent.ExecutionException;

public class DtUpdateOperation extends FutureOperation<CrdtResponse, RiakDtPB.DtUpdateResp>
{

    private final RiakDtPB.DtUpdateReq.Builder reqBuilder;

    private DtUpdateOperation(Builder builder)
    {
        this.reqBuilder = builder.reqBuilder;
    }

    @Override
    protected CrdtResponse convert(List<RiakDtPB.DtUpdateResp> rawResponse) throws ExecutionException
    {
        if (rawResponse.size() != 1)
        {
            throw new IllegalStateException("Expecting exactly one response, instead received " + rawResponse.size());
        }

        RiakDtPB.DtUpdateResp response = rawResponse.iterator().next();

        ByteArrayWrapper bucket = ByteArrayWrapper.unsafeCreate(reqBuilder.getBucket().toByteArray());

        ByteArrayWrapper key;
        if (reqBuilder.hasKey())
        {
            key = ByteArrayWrapper.unsafeCreate(reqBuilder.getKey().toByteArray());
        }
        else
        {
            key = ByteArrayWrapper.unsafeCreate(response.getKey().toByteArray());
        }

        CrdtResponse.Builder responseBuilder = new CrdtResponse.Builder(bucket, key);


        CrdtResponseConverter converter = new CrdtResponseConverter();
        CrdtElement element = converter.convert(response);
        responseBuilder.withCrdtElement(element);

        if (reqBuilder.hasType())
        {
            ByteArrayWrapper bucketType = ByteArrayWrapper.unsafeCreate(reqBuilder.getType().toByteArray());
            responseBuilder.withBucketType(bucketType);
        }

        if (response.hasContext())
        {
            ByteArrayWrapper context = ByteArrayWrapper.unsafeCreate(response.getContext().toByteArray());
            responseBuilder.withContext(context);
        }

        return responseBuilder.build();

    }

    @Override
    protected RiakMessage createChannelMessage()
    {
        return new RiakMessage(RiakMessageCodes.MSG_DtUpdateReq, reqBuilder.build().toByteArray());
    }

    @Override
    protected RiakDtPB.DtUpdateResp decode(RiakMessage rawMessage)
    {
        Operations.checkMessageType(rawMessage, RiakMessageCodes.MSG_DtUpdateResp);
        try
        {
            RiakDtPB.DtUpdateResp resp = RiakDtPB.DtUpdateResp.parseFrom(rawMessage.getData());
            return resp;
        }
        catch (InvalidProtocolBufferException ex)
        {
            throw new IllegalArgumentException("Invalid message received", ex);
        }
    }

    public static class Builder
    {
        private final RiakDtPB.DtUpdateReq.Builder reqBuilder = RiakDtPB.DtUpdateReq.newBuilder();
        
        public Builder(ByteArrayWrapper bucketName, ByteArrayWrapper bucketType)
        {
            if (null == bucketName || bucketName.length() == 0)
            {
                throw new IllegalArgumentException("Bucket name cannot be null or zero length");
            }
            reqBuilder.setBucket(ByteString.copyFrom(bucketName.unsafeGetValue()));

            if (null == bucketType || bucketType.length() == 0)
            {
                throw new IllegalArgumentException("Bucket type can not be null or zero length");
            }
            reqBuilder.setType(ByteString.copyFrom(bucketType.unsafeGetValue()));
        }

        /**
         * Set the key for this DtUpdateOperation.
         * <p>
         * If not set or null, a key is generated by Riak and returned in the
         * response.
         * </p>
         *
         * @param key the key.
         * @return a reference to this object.
         */
        public Builder withKey(ByteArrayWrapper key)
        {
            if (key != null)
            {
                if (key.length() == 0)
                {
                    throw new IllegalArgumentException("Key cannot be zero length");
                }
                else
                {
                    reqBuilder.setKey(ByteString.copyFrom(key.unsafeGetValue()));
                }
            }
            return this;
        }

        /**
         * Set the context for this operation.
         *
         * @param ctx a context from a previous fetch operation.
         * @return a reference to this object.
         */
        public Builder withContext(ByteArrayWrapper ctx)
        {
            if (null == ctx)
            {
                throw new IllegalArgumentException("Context cannot be null.");
            }
            reqBuilder.setContext(ByteString.copyFrom(ctx.unsafeGetValue()));
            return this;
        }

        /**
         * Set the W value for this DtUpdateOperation.
         * If not set the bucket default is used.
         *
         * @param w the W value.
         * @return a reference to this object.
         */
        public Builder withW(int w)
        {
            reqBuilder.setW(w);
            return this;
        }

        /**
         * Set the DW value for this DtUpdateOperation.
         * If not set the bucket default is used.
         *
         * @param dw the DW value.
         * @return a reference to this object.
         */
        public Builder withDw(int dw)
        {
            reqBuilder.setDw(dw);
            return this;
        }

        /**
         * Set the PW value for this DtUpdateOperation.
         * If not set the bucket default is used.
         *
         * @param pw the PW value.
         * @return a reference to this object.
         */
        public Builder withPw(int pw)
        {
            reqBuilder.setPw(pw);
            return this;
        }

        /**
         * Return the object after storing (including any siblings).
         *
         * @param returnBody true to return the object.
         * @return a reference to this object.
         */
        public Builder withReturnBody(boolean returnBody)
        {
            reqBuilder.setReturnBody(returnBody);
            return this;
        }


        /**
         * Set a timeout for this operation.
         *
         * @param timeout a timeout in milliseconds.
         * @return a reference to this object.
         */
        public Builder withTimeout(int timeout)
        {
            reqBuilder.setTimeout(timeout);
            return this;
        }

        /**
         * Set the n_val value for this operation.
         * <p>
         * <b>Do not use this unless you understand the ramifications</b>
         * </p>
         *
         * @param nval the n_val value
         * @return a reference to this object.
         */
        public Builder withNVal(int nval)
        {
            reqBuilder.setNVal(nval);
            return this;
        }

        /**
         * Set whether to use sloppy_quorum.
         * <p>
         * <b>Do not use this unless you understand the ramifications</b>
         * </p>
         *
         * @param sloppyQuorum true to use sloppy_quorum
         * @return a reference to this object.
         */
        public Builder withSloppyQuorum(boolean sloppyQuorum)
        {
            reqBuilder.setSloppyQuorum(sloppyQuorum);
            return this;
        }

        public DtUpdateOperation build()
        {
            return new DtUpdateOperation(this);
        }

        RiakDtPB.CounterOp getCounterOp(CounterOp op)
        {
            return RiakDtPB.CounterOp.newBuilder()
                .setIncrement(op.getIncrement())
                .build();
        }

        RiakDtPB.SetOp getSetOp(SetOp op)
        {
            RiakDtPB.SetOp.Builder setOpBuilder = RiakDtPB.SetOp.newBuilder();

            for (ByteArrayWrapper element : op.getAdds())
            {
                setOpBuilder.addAdds(ByteString.copyFrom(element.unsafeGetValue()));
            }

            for (ByteArrayWrapper element : op.getRemoves())
            {
                setOpBuilder.addRemoves(ByteString.copyFrom(element.unsafeGetValue()));
            }

            return setOpBuilder.build();
        }

        RiakDtPB.MapUpdate.FlagOp getFlagOp(FlagOp op)
        {
            return op.getEnabled()
                ? RiakDtPB.MapUpdate.FlagOp.ENABLE
                : RiakDtPB.MapUpdate.FlagOp.DISABLE;
        }

        ByteString getRegisterOp(RegisterOp op)
        {
            return ByteString.copyFrom(op.getValue().unsafeGetValue());
        }

        RiakDtPB.MapField getMapField(MapOp.MapField field)
        {
            RiakDtPB.MapField.Builder mapFieldBuilder = RiakDtPB.MapField.newBuilder();

            switch (field.type)
            {
                case SET:
                    mapFieldBuilder.setType(RiakDtPB.MapField.MapFieldType.SET);
                    break;
                case REGISTER:
                    mapFieldBuilder.setType(RiakDtPB.MapField.MapFieldType.REGISTER);
                    break;
                case MAP:
                    mapFieldBuilder.setType(RiakDtPB.MapField.MapFieldType.MAP);
                    break;
                case FLAG:
                    mapFieldBuilder.setType(RiakDtPB.MapField.MapFieldType.FLAG);
                    break;
                case COUNTER:
                    mapFieldBuilder.setType(RiakDtPB.MapField.MapFieldType.COUNTER);
                    break;
                default:
            }
            mapFieldBuilder.setName(ByteString.copyFrom(field.key.unsafeGetValue()));
            return mapFieldBuilder.build();
        }

        RiakDtPB.MapOp getMapOp(MapOp op)
        {
            RiakDtPB.MapOp.Builder mapOpBuilder = RiakDtPB.MapOp.newBuilder();

            for (MapOp.MapField field : op.getAdds())
            {
                mapOpBuilder.addAdds(getMapField(field));
            }

            for (MapOp.MapField field : op.getRemoves())
            {
                mapOpBuilder.addRemoves(getMapField(field));
            }

            for (MapOp.MapUpdate update : op.getUpdates())
            {
                RiakDtPB.MapUpdate.Builder mapUpdateBuilder =
                    RiakDtPB.MapUpdate.newBuilder();

                switch (update.field.type)
                {
                    case COUNTER:
                        mapUpdateBuilder.setCounterOp(getCounterOp((CounterOp) update.op));
                        break;
                    case FLAG:
                        mapUpdateBuilder.setFlagOp(getFlagOp((FlagOp) update.op));
                        break;
                    case MAP:
                        mapUpdateBuilder.setMapOp(getMapOp((MapOp) update.op));
                        break;
                    case REGISTER:
                        mapUpdateBuilder.setRegisterOp(getRegisterOp((RegisterOp) update.op));
                        break;
                    case SET:
                        mapUpdateBuilder.setSetOp(getSetOp((SetOp) update.op));
                        break;
                    default:
                        throw new IllegalStateException("Unknow datatype encountered");
                }

                mapUpdateBuilder.setField(getMapField(update.field));
                mapOpBuilder.addUpdates(mapUpdateBuilder);
            }

            return mapOpBuilder.build();

        }

        /**
         * Add a counter update operation to this operation.
         *
         * @param op the update
         * @return
         */
        public Builder withOp(CounterOp op)
        {
            reqBuilder.setOp(RiakDtPB.DtOp.newBuilder()
                .setCounterOp(getCounterOp(op)));

            return this;
        }

        /**
         * Add a map update operation to this operation.
         *
         * @param op the update
         * @return
         */
        public Builder withOp(MapOp op)
        {
            reqBuilder.setOp(RiakDtPB.DtOp.newBuilder()
                .setMapOp(getMapOp(op)));
            return this;
        }

        /**
         * Add a set update operation to this operation.
         *
         * @param op the update
         * @return
         */
        public Builder withOp(SetOp op)
        {

            reqBuilder.setOp(RiakDtPB.DtOp.newBuilder()
                .setSetOp(getSetOp(op)));

            return this;
        }

    }
}
